CREATE TABLE publisher
(
    id BIGSERIAL PRIMARY KEY,
    org_name VARCHAR(128) NOT NULL ,
    address TEXT NOT NULL
);

CREATE TABLE book
(
    id BIGSERIAL PRIMARY KEY,
    title TEXT NOT NULL,
    isbn VARCHAR(32) NOT NULL
);